package com.company;

import java.util.Arrays;

/**
 * Created by user on 10.01.2017.
 */
public class Day6 {
    public static String solve() {
        String[] arr = getInput().split("\n");
        ArrayObject[][] arr2 = new ArrayObject[arr[0].length()][ArrayObject.getArray().length];
        for (int i = 0; i < arr2.length; i++) {
            arr2[i] = ArrayObject.getArray();
        }
        String probability = "";
        for (String str : arr) {
            for (int i = 0; i < arr2.length; i++) {
                for (ArrayObject o : arr2[i]) {
                    if (str.charAt(i) == o.getCharacter()) {
                        o.increase();
                    }
                }
            }
        }

        for (ArrayObject[] a1 : arr2) {
            Arrays.sort(a1,(o1, o2)->o2.getCount()-o1.getCount());
            probability += a1[0].getCharacter();
        }
        return probability;
    }

    private static String getInput(){
        return "tmcezlum\n" +
                "afzwmyrz\n" +
                "ollxkaqs\n" +
                "oqvdutkr\n" +
                "ufzmsidi\n" +
                "wnidhqow\n" +
                "efgwivmh\n" +
                "endrsvkk\n" +
                "nraaoczx\n" +
                "yghmfumn\n" +
                "fcwrdzyt\n" +
                "qbbejygt\n" +
                "ohrzbtul\n" +
                "lmrarckg\n" +
                "frzhozsk\n" +
                "ahvqozmk\n" +
                "cnoxuqjm\n" +
                "njudcxbx\n" +
                "xjeohiim\n" +
                "sygfjxcx\n" +
                "fbmchcaa\n" +
                "qqggrcwq\n" +
                "vbcgurox\n" +
                "eujzkdmh\n" +
                "kbpinltk\n" +
                "posxqzam\n" +
                "rojnpogl\n" +
                "zvhruwqw\n" +
                "hvbrxcky\n" +
                "iqifiukd\n" +
                "xetwaptt\n" +
                "qvksnzoe\n" +
                "nulslfja\n" +
                "tphqwfte\n" +
                "ddencvfp\n" +
                "nhabbwcl\n" +
                "jefzkclw\n" +
                "txstxeio\n" +
                "yaaqxpdp\n" +
                "efewzeqa\n" +
                "teapznjk\n" +
                "jylnjhnf\n" +
                "jumelmrz\n" +
                "ziarkfwo\n" +
                "vklsvaca\n" +
                "uoyzpkbn\n" +
                "oovggzkn\n" +
                "ajvmcuon\n" +
                "gkztjkss\n" +
                "qnwohfwg\n" +
                "kxwtvaez\n" +
                "jwavozvo\n" +
                "qgqbbaoc\n" +
                "xzdepoxu\n" +
                "kbxhekyv\n" +
                "ceuqobnx\n" +
                "qlrejrjz\n" +
                "fvknhyqb\n" +
                "tfwsmaei\n" +
                "ofpzikkg\n" +
                "xggckiou\n" +
                "avcoljdv\n" +
                "vhzjtrwv\n" +
                "dyqnywkg\n" +
                "udobaedh\n" +
                "gncyxisz\n" +
                "oedldehj\n" +
                "ssmyewfv\n" +
                "ciaphyxw\n" +
                "fhizpimr\n" +
                "bjyeqyzh\n" +
                "owjojbzf\n" +
                "skdfqaeq\n" +
                "ubspxbix\n" +
                "truvdgua\n" +
                "ttvftscb\n" +
                "qjyxodqz\n" +
                "cakskune\n" +
                "okojmtim\n" +
                "rvrhaprz\n" +
                "iezxilxh\n" +
                "yalqlefr\n" +
                "rxygadto\n" +
                "hdszdagc\n" +
                "srqhzltw\n" +
                "vuinwxvi\n" +
                "jcunlnmn\n" +
                "jxolxqid\n" +
                "mnnjrghb\n" +
                "jogafqpd\n" +
                "ixdlwxwj\n" +
                "sttkgdyk\n" +
                "iqfeawey\n" +
                "zdlukwnn\n" +
                "odghxddl\n" +
                "eoflpjdw\n" +
                "haketaof\n" +
                "ylkfukna\n" +
                "pdwemhut\n" +
                "ryyhsryr\n" +
                "iapyhpba\n" +
                "wtgsqrtt\n" +
                "hctctzdi\n" +
                "ulnuyuex\n" +
                "bpxpdeqb\n" +
                "itbourhl\n" +
                "dztqwptk\n" +
                "gmmsltml\n" +
                "evnhvtiy\n" +
                "asjexlfo\n" +
                "sgxejmmg\n" +
                "qxbhjpmp\n" +
                "prauglcy\n" +
                "bulipmjg\n" +
                "xjrkceql\n" +
                "utehzgxa\n" +
                "ltvfsdrj\n" +
                "lnyazzkp\n" +
                "ddnndirm\n" +
                "bddvibpq\n" +
                "ajxjxdls\n" +
                "uidqyood\n" +
                "cjqffbdm\n" +
                "nzonwmsr\n" +
                "zmcesyao\n" +
                "wvfwtwuc\n" +
                "pwuqzzvg\n" +
                "eciaebxq\n" +
                "vxbuvava\n" +
                "yhalnneq\n" +
                "pejiyegy\n" +
                "tsopxjfn\n" +
                "ggzatxrg\n" +
                "lgnpyiko\n" +
                "einylipk\n" +
                "cwtgfpza\n" +
                "niddiicg\n" +
                "ctqbwhzb\n" +
                "mzpgsons\n" +
                "aqaxajai\n" +
                "fkwufqgn\n" +
                "dglewfob\n" +
                "xoqdxsnr\n" +
                "blxnybat\n" +
                "bohqqthr\n" +
                "qanfhczt\n" +
                "gkpxjfrb\n" +
                "zmewqucy\n" +
                "atuodurb\n" +
                "suiitdqe\n" +
                "usywjzqc\n" +
                "voltqnvd\n" +
                "ppstzuzb\n" +
                "ncxkbwul\n" +
                "hgivkyyq\n" +
                "bldyxpov\n" +
                "yvjbraai\n" +
                "fhqawceq\n" +
                "nrmjvhnh\n" +
                "kpwxogac\n" +
                "trtzfnkp\n" +
                "pczcsgns\n" +
                "rfjdromo\n" +
                "uncmnnjj\n" +
                "eordqsju\n" +
                "rhvpcncs\n" +
                "hrokpyig\n" +
                "bkszmpef\n" +
                "krugmwkb\n" +
                "syvtsdek\n" +
                "vigizldv\n" +
                "vldwtfmv\n" +
                "ckcbqkrf\n" +
                "dtvjipcw\n" +
                "ampjmdpd\n" +
                "kcirijwv\n" +
                "zzufovbr\n" +
                "olexgnqh\n" +
                "llxddfsh\n" +
                "wfnnkivb\n" +
                "dzvcoxpi\n" +
                "wpcwuqoc\n" +
                "nejgfqvm\n" +
                "mgbjcbst\n" +
                "uglwuejg\n" +
                "rwfcpnpp\n" +
                "dbfycvwm\n" +
                "hisynlnw\n" +
                "gglqswni\n" +
                "wpmiixuf\n" +
                "rqbfxlef\n" +
                "lsupxzeu\n" +
                "uqrzsowl\n" +
                "xqmgmnyk\n" +
                "gzdfdbtb\n" +
                "aoyujvtz\n" +
                "zmhsbsde\n" +
                "xnmsgyvk\n" +
                "gszwzotk\n" +
                "fkbphiti\n" +
                "lffmpdda\n" +
                "plotuwbi\n" +
                "hakfuxeb\n" +
                "cpqzjdjb\n" +
                "foqwhfis\n" +
                "ctevnjly\n" +
                "bbnuoohx\n" +
                "zjndqgbv\n" +
                "ftmrakmg\n" +
                "yphljbse\n" +
                "vcmmtout\n" +
                "ishcbwpn\n" +
                "oysaacfd\n" +
                "upawmrwj\n" +
                "cexlaadr\n" +
                "cezsoibf\n" +
                "yydnylal\n" +
                "mieypczr\n" +
                "ltbuvmfu\n" +
                "ekumekic\n" +
                "krbiejuo\n" +
                "cyweeeht\n" +
                "lugkftlh\n" +
                "pohkdvai\n" +
                "xgoxbacm\n" +
                "ingicfit\n" +
                "dclavjqp\n" +
                "dnzgfbrc\n" +
                "jssnhcfu\n" +
                "txykgvhl\n" +
                "uwvgyzgz\n" +
                "jecfzcoi\n" +
                "yaktumqx\n" +
                "oqehhika\n" +
                "voqmtwam\n" +
                "wchhskdh\n" +
                "kxjzeygs\n" +
                "krfjungf\n" +
                "iqamjkgh\n" +
                "ajaxlbcr\n" +
                "mfrdjjwz\n" +
                "jvqfkkjt\n" +
                "mupueoje\n" +
                "ozvctxzd\n" +
                "qneodvvw\n" +
                "zisckhyc\n" +
                "yxgudchh\n" +
                "oapmbpbc\n" +
                "pyizuqnn\n" +
                "ttnblbho\n" +
                "xdpiahgx\n" +
                "lyerpyzv\n" +
                "dzslbegp\n" +
                "fvujdszc\n" +
                "qhuhvkej\n" +
                "wxktwmez\n" +
                "irrqradv\n" +
                "xtbqoxyg\n" +
                "nhlrfrgy\n" +
                "gocvpvlp\n" +
                "bwybesby\n" +
                "rvewprlo\n" +
                "elwmmcos\n" +
                "fertmhyj\n" +
                "qhxooqtq\n" +
                "gzdaipgn\n" +
                "yqfmniyt\n" +
                "gornoejg\n" +
                "wqgsxzys\n" +
                "kxqaletd\n" +
                "ikuvaeft\n" +
                "essiqowb\n" +
                "ymohhvfu\n" +
                "kzjynqhe\n" +
                "ooxnssfp\n" +
                "hpnozozp\n" +
                "kdxkokxe\n" +
                "rwredkrn\n" +
                "znmrmswj\n" +
                "svtkdsuu\n" +
                "ibjqwhwi\n" +
                "mknydjrv\n" +
                "opchsgmr\n" +
                "tbyvuatt\n" +
                "igevmbpk\n" +
                "expjknbc\n" +
                "kzboboox\n" +
                "usoxsikr\n" +
                "fizzvucq\n" +
                "rvjomwnd\n" +
                "sgfcwqdl\n" +
                "ocacgxpj\n" +
                "mropbfvf\n" +
                "xexycbuo\n" +
                "qngxnnud\n" +
                "itmenmlm\n" +
                "dyaqaifs\n" +
                "jwgtqejq\n" +
                "eyeaavrj\n" +
                "vwyjauhk\n" +
                "hqajvjkh\n" +
                "ddvhuacy\n" +
                "gjgrgtll\n" +
                "mgawuelx\n" +
                "lmdgzggf\n" +
                "pbtgkvxc\n" +
                "svwklnwu\n" +
                "kvtsovnm\n" +
                "oybxcuqk\n" +
                "ufwkjtlj\n" +
                "xkrgfyad\n" +
                "kdgdjzqp\n" +
                "iqdgesbu\n" +
                "mxpocjsl\n" +
                "rmwvihpw\n" +
                "bpbftisr\n" +
                "kgtgxxqw\n" +
                "ypwjafxu\n" +
                "hihxitsz\n" +
                "lnntwahr\n" +
                "ssecoqkz\n" +
                "ynktphtd\n" +
                "skwfmfpw\n" +
                "bihrglvz\n" +
                "xzkjkgjm\n" +
                "cuozrxqe\n" +
                "qmcfrurm\n" +
                "tphowbli\n" +
                "zvzwyhrv\n" +
                "vzlfbuor\n" +
                "vblsrrba\n" +
                "lakiynlc\n" +
                "afomthrw\n" +
                "rbgtoyfq\n" +
                "ahkqljen\n" +
                "gamoerak\n" +
                "wumjelwi\n" +
                "vqimktjy\n" +
                "levvfcsq\n" +
                "euwrqnjp\n" +
                "fapllntx\n" +
                "vyzlxslf\n" +
                "rwhcbrvz\n" +
                "txpficpp\n" +
                "mbwpimjr\n" +
                "zohppwog\n" +
                "zdrsdecc\n" +
                "uaxqlvsh\n" +
                "ykerbsdc\n" +
                "aecktaff\n" +
                "wrtdufue\n" +
                "gykyrwcv\n" +
                "sesrvnsp\n" +
                "hmopnqyy\n" +
                "tfuulvec\n" +
                "jdokvsfw\n" +
                "jwkhzpaf\n" +
                "mjvzffxn\n" +
                "pctkfrtb\n" +
                "wfiwcoxg\n" +
                "qodzwvbg\n" +
                "brcaggnu\n" +
                "jjjrrtiu\n" +
                "ktkobacy\n" +
                "nahinlmj\n" +
                "nszbvcmi\n" +
                "nfvbldhe\n" +
                "tjweqfgt\n" +
                "crabmuxk\n" +
                "affxwlpf\n" +
                "mpominpv\n" +
                "yufjtaaa\n" +
                "hzzhmsyx\n" +
                "plwdkozp\n" +
                "ozbgwwvd\n" +
                "pplerubj\n" +
                "wzumeuqo\n" +
                "ksynbxaf\n" +
                "yxeircsj\n" +
                "gaqlykne\n" +
                "irsltmrz\n" +
                "jifivecj\n" +
                "vhwsstkq\n" +
                "mjiiiuab\n" +
                "nkimvhvg\n" +
                "memuhxrh\n" +
                "tjvbzypn\n" +
                "glebcdpn\n" +
                "zrmcpufo\n" +
                "imxlujrn\n" +
                "acftqbcf\n" +
                "symmrhuj\n" +
                "lqkrybxd\n" +
                "jsyxqzqt\n" +
                "xbqjvjxl\n" +
                "qwqsvysm\n" +
                "ddjypobl\n" +
                "rwxyfjby\n" +
                "wpoiklyi\n" +
                "eiftosiu\n" +
                "cabwkqhx\n" +
                "yxtbhlxo\n" +
                "heismnzr\n" +
                "yaduhfgm\n" +
                "nghplvvs\n" +
                "lwukrqdx\n" +
                "ifjqghtk\n" +
                "qclffqxm\n" +
                "cuszvrgk\n" +
                "ocshztws\n" +
                "hipeodcu\n" +
                "qnbgnllz\n" +
                "qsuogdmr\n" +
                "eusogkvt\n" +
                "rddealkr\n" +
                "fjrrvsco\n" +
                "nugopflj\n" +
                "bhgbdkxs\n" +
                "fthcqpao\n" +
                "tkdvyegv\n" +
                "tbvpgueq\n" +
                "ahfagxlm\n" +
                "cipkqfxj\n" +
                "vqqcipuc\n" +
                "mugdchdl\n" +
                "wwjpnife\n" +
                "purpypnv\n" +
                "cqzunigd\n" +
                "nlnvjhbd\n" +
                "hhiqrzod\n" +
                "fwjhmdij\n" +
                "wkpvakif\n" +
                "bjrytvwo\n" +
                "uosbgqjb\n" +
                "bdmfzjcy\n" +
                "dxlqldzl\n" +
                "akqbtwvs\n" +
                "wbxschlg\n" +
                "mrzksrhs\n" +
                "jmvueuih\n" +
                "ebxpjnhp\n" +
                "llsogwyw\n" +
                "peyzimia\n" +
                "mufdkyny\n" +
                "dlvxntre\n" +
                "dyfyazrx\n" +
                "aarkcrwe\n" +
                "qqacegoh\n" +
                "rbiqykai\n" +
                "tbnkymsk\n" +
                "ebtsieby\n" +
                "uhyjeeba\n" +
                "ahpywtnx\n" +
                "gyvacpuf\n" +
                "frcyslud\n" +
                "mwwnxofu\n" +
                "jzyabbkj\n" +
                "cctdoztv\n" +
                "jztmavpd\n" +
                "sacgyoii\n" +
                "gnqiydic\n" +
                "ggdrerzq\n" +
                "lduphshn\n" +
                "hctmpgih\n" +
                "kqabzyjt\n" +
                "ppkztsay\n" +
                "pnusnowm\n" +
                "ulyvxfkp\n" +
                "vmlapyyt\n" +
                "zifxarmp\n" +
                "vnpzxhjb\n" +
                "raewumao\n" +
                "wejyiymi\n" +
                "gjbdfjzy\n" +
                "bxhlwziy\n" +
                "rsqlgthf\n" +
                "xtkaltqu\n" +
                "smiarmpw\n" +
                "xdypfzem\n" +
                "yleuggnb\n" +
                "wgphfsve\n" +
                "xgqmyqhq\n" +
                "iyfrymtc\n" +
                "bwhjkhfl\n" +
                "aftctjug\n" +
                "seibsuof\n" +
                "ngcdnmxw\n" +
                "ltxyudxa\n" +
                "xpwqkgdl\n" +
                "hagwixkv\n" +
                "lhtlmxqw\n" +
                "dcineqxs\n" +
                "nzdrjynu\n" +
                "vmytcguy\n" +
                "ymsuzmox\n" +
                "lkzvgcgh\n" +
                "dfjgzjdn\n" +
                "rvmgejgk\n" +
                "dcxdrgpz\n" +
                "bhjsceuv\n" +
                "nhpllxmo\n" +
                "gkotvtsu\n" +
                "uubvdkjg\n" +
                "zjnerxhq\n" +
                "butazmez\n" +
                "szzvqyzs\n" +
                "fpchqsei\n" +
                "xfsvriyr\n" +
                "vxodutyh\n" +
                "zsilhmba\n" +
                "rvacqpwj\n" +
                "hjewdrtx\n" +
                "bylcpgfs\n" +
                "qtntvgfq\n" +
                "ioqldhye\n" +
                "wlrbwapp\n" +
                "nlptloss\n" +
                "znnybfvl\n" +
                "einvacbu\n" +
                "kyziepsr\n" +
                "fthuwmlv\n" +
                "pmkbhvdn\n" +
                "xuxngboe\n" +
                "tpoinkzc\n" +
                "zwbnhlwp\n" +
                "usuusbin\n" +
                "jiulcmsq\n" +
                "elcusgvu\n" +
                "frclhdyo\n" +
                "pvmirlch\n" +
                "jvrjfxmb\n" +
                "sxmtcrsw\n" +
                "ccfkmgmw\n" +
                "mdnibgld\n" +
                "idmojsza\n" +
                "hsjvyoua\n" +
                "smhwbpax\n" +
                "pgcozahq\n" +
                "dstdnwle\n" +
                "aiikfrxt\n" +
                "kmbnsppa\n" +
                "wsxcbwze\n" +
                "hqyunies\n" +
                "mfrxeqyw\n" +
                "zikpwtqz\n" +
                "zckxtclz";
    }

    private static String getAltInput(){
        return "eedadn\n" +
                "drvtee\n" +
                "eandsr\n" +
                "raavrd\n" +
                "atevrs\n" +
                "tsrnev\n" +
                "sdttsa\n" +
                "rasrtv\n" +
                "nssdts\n" +
                "ntnada\n" +
                "svetve\n" +
                "tesnvt\n" +
                "vntsnd\n" +
                "vrdear\n" +
                "dvrsen\n" +
                "enarar";
    }

}
